In [2]:
import pandas as pd  
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
from sklearn.svm import SVC

In [3]:
train = pd.read_csv('New folder/train.csv')
test = pd.read_csv('New folder/test.csv')

In [4]:
train.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [5]:
test.head(5)

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [6]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [7]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Pclass       418 non-null    int64
 2   Name         418 non-null    object
 3   Sex          418 non-null    object
 4   Age          332 non-null    float64
 5   SibSp        418 non-null    int64
 6   Parch        418 non-null    int64
 7   Ticket       418 non-null    object
 8   Fare         417 non-null    float64
 9   Cabin        91 non-null     object
 10  Embarked     418 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 36.1+ KB

In [8]:
train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
test.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [10]:
train.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [11]:
test.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [12]:
train.fillna(train['Age'].mean(),inplace=True)

In [13]:
train['Age'].isnull().sum()

np.int64(0)

In [14]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer

In [15]:
train['Cabin'].unique()

array([np.float64(29.69911764705882), 'C85', 'C123', 'E46', 'G6', 'C103',
       'D56', 'A6', 'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28',
       'C83', 'F33', 'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110',
       'B58 B60', 'E101', 'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19',
       'A7', 'C49', 'F4', 'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93',
       'C78', 'D35', 'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118',
       'D7', 'A19', 'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [16]:
# Extract the first letter, fill NaNs with 'U' for Unknown
train['Deck'] = train['Cabin'].str[0]
train['Deck'] = train['Deck'].fillna('U')

In [17]:
# Grouping A, G, and T into 'Others' or similar categories
train['Deck'] = train['Deck'].replace(['T', 'G', 'A'], 'Other')

In [18]:
train

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,29.699118,S,U
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,29.699118,S,U
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,C
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,29.699118,S,U
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,29.699118,S,U
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,B
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,29.699118,S,U
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,29.699118,Q,U

In [19]:
train.drop(columns='PassengerId')

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck
0,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,29.699118,S,U
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C85,C,C
2,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,29.699118,S,U
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,C123,S,C
4,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,29.699118,S,U
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,29.699118,S,U
887,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,B42,S,B
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,29.699118,S,U
889,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C148,C,C
890,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,29.699118,Q,U

In [20]:
# Extract the title using Regex
train['Title'] = train['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)

# Group rare titles (Mlle, Ms, Lady -> Miss/Mrs)
train['Title'] = train['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')

# NOW you can safely drop the Name column
train.drop('Name', axis=1, inplace=True)

In [21]:
train

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Deck,Title
0,1,0,3,male,22.000000,1,0,A/5 21171,7.2500,29.699118,S,U,Mr
1,2,1,1,female,38.000000,1,0,PC 17599,71.2833,C85,C,C,Mrs
2,3,1,3,female,26.000000,0,0,STON/O2. 3101282,7.9250,29.699118,S,U,Miss
3,4,1,1,female,35.000000,1,0,113803,53.1000,C123,S,C,Mrs
4,5,0,3,male,35.000000,0,0,373450,8.0500,29.699118,S,U,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.000000,0,0,211536,13.0000,29.699118,S,U,Rare
887,888,1,1,female,19.000000,0,0,112053,30.0000,B42,S,B,Miss
888,889,0,3,female,29.699118,1,2,W./C. 6607,23.4500,29.699118,S,U,Miss
889,890,1,1,male,26.000000,0,0,111369,30.0000,C148,C,C,Mr
890,891,0,3,male,32.000000,0,0,370376,7.7500,29.699118,Q,U,Mr

In [22]:
train['Sex'] = train['Sex'].map({'female':0,'male':1})

In [23]:
train['Group_Size'] = train.groupby('Ticket')['Ticket'].transform('count')
train['Real_Fare'] = train['Fare'] / train['Group_Size']

In [24]:
train['Title'].unique()

array(['Mr', 'Mrs', 'Miss', 'Master', 'Rare', 'Mme', 'Ms', 'Mlle'],
      dtype=object)

In [25]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [26]:
train['Title'] = train['Title'].map({'Mr':0,'Mrs':1,'Miss':2,'Master':3,'Rare':4,'Mme':5,'Ms':6,'Mlle':8})

In [27]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 1. Encode Deck
le = LabelEncoder()
train['Deck'] = le.fit_transform(train['Deck'])

# 2. Encode Title (One-Hot)
train = pd.get_dummies(train, columns=['Title'], prefix='T')

# 3. Final Drop
# You can now drop the columns you used to create these
# (e.g., Name, Cabin, Ticket, and the original Fare)
columns_to_drop = ['Name', 'Ticket', 'Cabin', 'Fare', 'PassengerId']
train.drop([col for col in columns_to_drop if col in train.columns], axis=1, inplace=True)

In [28]:
train

,Survived,Pclass,Sex,Age,SibSp,Parch,Embarked,Deck,Group_Size,Real_Fare,T_0,T_1,T_2,T_3,T_4,T_5,T_6,T_8
0,0,3,1,22.000000,1,0,S,6,1,7.2500,True,False,False,False,False,False,False,False
1,1,1,0,38.000000,1,0,C,1,1,71.2833,False,True,False,False,False,False,False,False
2,1,3,0,26.000000,0,0,S,6,1,7.9250,False,False,True,False,False,False,False,False
3,1,1,0,35.000000,1,0,S,1,2,26.5500,False,True,False,False,False,False,False,False
4,0,3,1,35.000000,0,0,S,6,1,8.0500,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,S,6,1,13.0000,False,False,False,False,True,False,False,False
887,1,1,0,19.000000,0,0,S,0,1,30.0000,False,False,True,False,False,False,False,False
888,0,3,0,29.699118,1,2,S,6,2,11.7250,False,False,True,False,False,False,False,False
889,1,1,1,26.000000,0,0,C,1,1,30.0000,True,False,False,False,False,False,False,False
890,0,3,1,32.000000,0,0,Q,6,1,7.7500,True,False,False,False,False,False,False,False

In [29]:
train['Embarked'].unique()

array(['S', 'C', 'Q', np.float64(29.69911764705882)], dtype=object)

In [30]:
# Fill Embarked with 'S' (the mode)
train['Embarked'] = train['Embarked'].fillna('S')

In [31]:
# Fill Age with the mean
train['Age'] = train['Age'].fillna(train['Age'].mean())

In [32]:
impute_values = {
    'Age': train['Age'].mean(),
    'Embarked': 'S',
    'Real_Fare': train['Real_Fare'].median() # Use the new name!
}

train.fillna(value=impute_values, inplace=True)

In [33]:
train

,Survived,Pclass,Sex,Age,SibSp,Parch,Embarked,Deck,Group_Size,Real_Fare,T_0,T_1,T_2,T_3,T_4,T_5,T_6,T_8
0,0,3,1,22.000000,1,0,S,6,1,7.2500,True,False,False,False,False,False,False,False
1,1,1,0,38.000000,1,0,C,1,1,71.2833,False,True,False,False,False,False,False,False
2,1,3,0,26.000000,0,0,S,6,1,7.9250,False,False,True,False,False,False,False,False
3,1,1,0,35.000000,1,0,S,1,2,26.5500,False,True,False,False,False,False,False,False
4,0,3,1,35.000000,0,0,S,6,1,8.0500,True,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,S,6,1,13.0000,False,False,False,False,True,False,False,False
887,1,1,0,19.000000,0,0,S,0,1,30.0000,False,False,True,False,False,False,False,False
888,0,3,0,29.699118,1,2,S,6,2,11.7250,False,False,True,False,False,False,False,False
889,1,1,1,26.000000,0,0,C,1,1,30.0000,True,False,False,False,False,False,False,False
890,0,3,1,32.000000,0,0,Q,6,1,7.7500,True,False,False,False,False,False,False,False

In [34]:
train['Embarked'].unique()

array(['S', 'C', 'Q', np.float64(29.69911764705882)], dtype=object)

In [35]:
import numpy as np

# Convert the column to string first to make matching easier
train['Embarked'] = train['Embarked'].astype(str)

# Replace the specific 'mean' string with 'S'
# Note: When you converted to string, the number becomes '29.69911764705882'
train.loc[train['Embarked'].str.contains('29.69'), 'Embarked'] = 'S'

# Verify it worked
print(train['Embarked'].unique())

['S' 'C' 'Q']

In [36]:
# Manual Mapping
embarked_mapping = {"S": 0, "C": 1, "Q": 2}
train['Embarked'] = train['Embarked'].map(embarked_mapping)

In [37]:
x = train[train.columns[1:]]
y = train['Survived']
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=42)

In [38]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=250,max_depth=5,random_state=42)
model.fit(x_train,y_train)

RandomForestClassifier(max_depth=5, n_estimators=250, random_state=42)

In [39]:
rf = model.predict(x_test)

In [40]:
print(classification_report(y_test,rf))

              precision    recall  f1-score   support

           0       0.82      0.87      0.85       134
           1       0.79      0.72      0.75        89

    accuracy                           0.81       223
   macro avg       0.81      0.80      0.80       223
weighted avg       0.81      0.81      0.81       223

In [41]:
from sklearn.model_selection import train_test_split

# Split your training data (891 rows) into training and validation
x_train, x_val, y_train, y_val = train_test_split(x, y, test_size=0.2, random_state=42)

# Train the model
model.fit(x_train, y_train)

# Predict on the validation set
y_pred = model.predict(x_val)

# Now they will both be the same length!
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

           0       0.81      0.88      0.84       105
           1       0.80      0.72      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179

In [48]:
import pandas as pd
import numpy as np

# 1. Reload raw data to ensure no columns are missing from memory
train_orig = pd.read_csv('New folder/train.csv')
test_df = pd.read_csv('New folder/test.csv')

# 2. Extract specific values from training data to apply to test (Prevents data leakage)
age_mean = train_orig['Age'].mean()
fare_median = train_orig['Fare'].median()

# 3. Handle Missing Values in Test
test_df['Age'] = test_df['Age'].fillna(age_mean)
test_df['Fare'] = test_df['Fare'].fillna(fare_median)
test_df['Embarked'] = test_df['Embarked'].fillna('S')

# 4. Feature Engineering: Deck
test_df['Deck'] = test_df['Cabin'].str[0].fillna('U')
test_df['Deck'] = test_df['Deck'].replace(['T', 'G', 'A'], 'Other')
# Use the LabelEncoder 'le' from your notebook
test_df['Deck'] = le.transform(test_df['Deck'])

# 5. Feature Engineering: Title
test_df['Title'] = test_df['Name'].str.extract(' ([A-Za-z]+)\.', expand=False)
test_df['Title'] = test_df['Title'].replace(['Lady', 'Countess','Capt', 'Col','Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], 'Rare')
title_mapping = {'Mr':0,'Mrs':1,'Miss':2,'Master':3,'Rare':4,'Mme':5,'Ms':6,'Mlle':8}
test_df['Title'] = test_df['Title'].map(title_mapping).fillna(0)

# 6. Feature Engineering: Group Size & Real Fare
test_df['Group_Size'] = test_df.groupby('Ticket')['Ticket'].transform('count')
test_df['Real_Fare'] = test_df['Fare'] / test_df['Group_Size']

# 7. Mappings
test_df['Sex'] = test_df['Sex'].map({'female':0,'male':1})
test_df['Embarked'] = test_df['Embarked'].map({"S": 0, "C": 1, "Q": 2})

# 8. One-Hot Encode Title (To create T_0, T_1, etc.)
test_df = pd.get_dummies(test_df, columns=['Title'], prefix='T')

# 9. Column Alignment: Ensure test has the exact same 17 features as 'x'
for col in x.columns:
    if col not in test_df.columns:
        test_df[col] = 0

# Select and order features exactly like training
X_test_final = test_df[x.columns]

# 10. Prediction & CSV Generation
final_predictions = model.predict(X_test_final)

submission = pd.DataFrame({
    "PassengerId": pd.read_csv('New folder/test.csv')["PassengerId"],
    "Survived": final_predictions
})

submission.to_csv('submission.csv', index=False)
print("Successfully created 'submission.csv' with 418 rows!")

Successfully created 'submission.csv' with 418 rows!